### ISSUE TITLE
Mirgrate the bindings to roc-toolkit 0.2

### ISSUE THREAD

**Issue by Asalle** [roc-streaming/roc-go#30]

**Comment by Asalle** [comment]
@gavv yes, of course! I apologize for my prolonged absence, things have been crazy. I will be available for review!

**Comment by gavv** [comment]
Great! No worries! I also had difficulties with free time last year. Good news are that this summer and autumn I had some paid work related to roc, and recently we have open-sourced big part of that work. I'm now finishing documentation update needed to release 0.2, and will update bindings as well.
