### ISSUE TITLE
Take headers and lib from pkg-config 

### ISSUE THREAD

**Issue by Asalle** [roc-streaming/roc-go#4]
Currently we have hardcoded `/usr/lib/roc` path that is not always where you have your headers/lib. Let's take that info from pkg-config.

**Comment by gavv** [comment]
I've updated https://github.com/roc-project/roc/issues/271

**Comment by Asalle** [comment]
Can you add a label "blocked" or "camping"? Or can you give me the permissions to add tags? :3

**Comment by gavv** [comment]
Hm, I'm don't see such a permission in settings.

Probably it's better to user projects for that? Like we do it in core: https://github.com/roc-project/roc/projects/2

I've enabled projects for the repo, you can try it (do you have permissions?). Or I can just create the label, I'm OK with that too.

**Comment by Asalle** [comment]
Have no permissions to add a label, also I don't see the board. But no
worries, I don't need it too much!

**Comment by gavv** [comment]
> Have no permissions to add a label, also I don't see the board.

Not good. I've selected a different permission level (triage -> write) for the go team, could you check now?

**Comment by Asalle** [comment]
works! thanks

**Comment by gavv** [comment]
.pc generation & installation landed in develop branch. `scons install` will now install `roc.pc`.

cc @fusuiyi123

**Comment by Asalle** [comment]
Yay! We can start using it in go bindings!

**Comment by Asalle** [comment]
now that I've looked into it, is this feature relevant? The only place where we use the C includes are comments like 
```
/*
#include <roc/address.h>
*/
import "C"
```
which work regardless if one uses pkg-config or just installed them with their distribution's package manager.

**Comment by gavv** [comment]
If the user installed roc into a prefix which is not in default include or library search path list, compilation will fail. pkg-config will solve this issue.

A real-world examples. When you're using SoX library you should write:

```
#include <sox.h>
```

On most distros, sox.h is located at /usr/include/sox.h and include works without any pkg-config.

However, on some CentOS version, for some reason maintainers decided to install that file at /usr/include/sox/sox.h. On those CentOS systems pkg-config for SoX returns `-I/usr/include/sox`. If you're using pkg-config, everything works, but without it your include fails.

So yes, we still need pkg-config, though it's not critical.

Note that pkg-config generation is currently available only in develop, while bindings are using master.

**Comment by gavv** [comment]
Example of using pkg-config with cgo: https://github.com/aam335/speexdsp/blob/master/speexdsp.go#L4

**Comment by Asalle** [comment]
cool, then I'll test it locally with develop, push to a branch and create a pr later when the changes will be available on master (they are still not there as of now)

**Comment by gavv** [comment]
We'll also need to migrate bindings to new api from 0.2.

**Comment by gavv** [comment]
I guess we need a separate issue and branch for that.

**Comment by Asalle** [comment]
@gavv did you release 0.2 already? cannot find it anywhere

**Comment by gavv** [comment]
@Asalle Hi, no, 0.2 isn't released yet. It's still in the `develop` branch. The API of 0.2 is mostly stabilized; it will be changed a bit before final release, but I expect only minor changes. So I think we can start migration of bindings to 0.2, maybe in a separate branch (maybe also call it `develop` for convenience).
