### ISSUE TITLE
Add unit tests for sender and receiver errors

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#41]
It would be nice to cover with unit tests errors returned by:

* OpenSender, OpenReceiver
* Sender.Connect, Receiver.Bind
* Sender.WriteFloats, Receiver.ReadFloats

See:

https://coveralls.io/builds/55438429/source?filename=roc%2Fsender.go
https://coveralls.io/builds/55438429/source?filename=roc%2Freceiver.go

No need to cover panics: mostly there is no way to cover them.

**Comment by Darrellbor** [comment]
@gavv I would like to handle this

**Comment by gavv** [comment]
Landed
