### ISSUE TITLE
 Add version information to API

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#47]
C library provides version info: https://roc-streaming.org/toolkit/docs/api/reference.html#roc-version

It would be nice to add this feature to the go library too. We need to provide two versions actually: version of the native library (libroc), and version of the bindings (which may be slightly different).

Versions of the bindings can be obtained using https://pkg.go.dev/runtime/debug

**Comment by dhanusaputra** [comment]
hi gavv, can i help with this? thanks

**Comment by gavv** [comment]
You're welcome!
