### ISSUE TITLE
Add error handling to go2cStr

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#50]
Currently, if go2cStr meets zero byte in the middle or in the end of the string, it stops early (and also oddly produces two zero bytes instead of one).

Instead, it should report error that the input string is incorrect. Everywhere where we call go2cStr, we should check error and report it to user.

**Comment by PiotrLewandowski323** [comment]
Hi,
I'd like to work on this issue.

**Comment by gavv** [comment]
@PiotrLewandowski323 thanks!

But we should wait until #49 is merged (I think it'll happen soon)

@ortex FYI

**Comment by gavv** [comment]
@PiotrLewandowski323 #49 is merged now!
