### ISSUE TITLE
Add test for log message struct

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#52]
Add new test TestLog_Message, similar to TestLog_Func, which does the following:

* sets log level to LogTrace
* installs log handler using SetLoggerFunc
* waits until log handler is called with a message of level LogTrace (trace messages have most fields)
* and inspects received message

It should check that message's field Level is trace, and fields Module, File, Line, Time, Pid, Tid, Text are non-empty / non-zero.

**Comment by Darrellbor** [comment]
i would like to help out with this issue although i'm yet to successfully run the codebase on my end

**Comment by Krishhna04** [comment]
Hi I would love to do this ,i am new to open source ,if you can exlain little more about the issue ,i will be able to provide solution in go

**Comment by gavv** [comment]
Hi! Feel free to ask if you have specific questions.

**Comment by Darrellbor** [comment]
@gavv i'd like to help out with this

**Comment by gavv** [comment]
Thanks!
