### ISSUE TITLE
Add debug logging

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#70]
Add debug logs for all public methods of Context, Sender, and Receiver, except real-time operations: ReadFloats and WriteFloats.

We should log beginning and end of each operation, so that by looking at logs we can easily say when we entered and exited native code. We can do it by adding something like this to each method (pseudocode):

```
log(...)
defer log(...)
```

We should include arguments passed to methods to logs. For enums, let's use stringer tool to generate String() method. https://pkg.go.dev/golang.org/x/tools/cmd/stringer

During Context opening, we should also log versions of bindings and native lib, reported by Version() call.

Logs should be passed to the handler registered via SetLoggerFunc() with log level set to debug. They should take into account log level set by SetLogLevel().

**Comment by gavv** [comment]
Thanks!

**Comment by Darrellbor** [comment]
@gavv I need a bit more context on this.
I believe the objective is to push the logs through the log handler on `log.go`

A possible log impl might look like 
```go
SetLogLevel(LogDebug)
defer SetLogLevel(defaultLogLevel)

SetLoggerFunc(func(msg LogMessage) {
	//what happens here	
})
defer SetLoggerFunc(nil)
```

and would this be replicated across `context`, `receiver` and `sender`?
I'm probably not seeing it the right way... please advise

**Comment by gavv** [comment]
> I believe the objective is to push the logs through the log handler on log.go

Right.

> A possible log impl might look like

I don't see why you may need to modify level and handler.

What you need is to push log message to the registered handler. Also you need to check what level is set, and don't push message if the level is not high enough (if level is info, you shouldn't push debug messages).

See #74, it reworks log handling a bit. I suggest you to base your work on top of that branch (we'll merge it soon).

In that branch, log handler is invoked in goroutine:

```go
func loggerRoutine() {
	for message := range loggerCh {
		fn := loggerFunc.Load().(LoggerFunc)
		if fn != nil {
			fn(message)
		}
	}
}
```

So what you need is to push your messages to `loggerCh`.

You can add a new function like this:

```go
func logWrite(level, text) {
    // don't forget to check level
    loggerCh <- LogMessage{
        // fill fields from args
    }
}
```

and then use this func from context, sender, receiver, etc.
