### ISSUE TITLE
Add version checking

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#71]
When any non-method public function is called first time (except Version func), we need to call Version() to retrieve versions of native lib and go bindings, and check the following invariant:

* major versions are equal
* minor version of bindings is greater than or equal to minor version of native lib

(See "Versioning" section in Readme for explanation)

Non-method public functions include: OpenContext, OpenSender, OpenReceicer, SetLogger, SetLoggerFunc, SetLogLevel.

If the invariant is not satisfied, we should panic. Panic message should include both versions and reason.

**Comment by fastbyt3** [comment]
Hey o/ Can I take a shot on this?

**Comment by gavv** [comment]
Sure, thanks!

**Comment by fastbyt3** [comment]
Sorry but I'm pretty new to open source contribs. Is it cool with you if i DM (any platform works) you regarding some qs i have?

**Comment by gavv** [comment]
@fastbyt3 welcome to join `#roc-streaming-dev:matrix.org` on matrix

https://roc-streaming.org/toolkit/docs/about_project/contacts.html
