### ISSUE TITLE
Use time.Duration for time intervals

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#83]
Find fields in SenderConfig and ReceiverConfig that hold time intervals, and switch their type from plane integer to time.Duration. Adjust comments and implementation accordingly.

Fields of interest:

* SenderConfig:

  * [x] PacketLength

* ReceiverConfig

  * [x] TargetLatency
  * [x] MaxLatencyOverrun
  * [x] MaxLatencyUnderrun
  * [x] NoPlaybackTimeout
  * [x] BrokenPlaybackTimeout
  * [x] BreakageDetectionWindow

To avoid copy-paste in implementation, we'll need to add new conversion functions (between time.Duration and C.longlong / C.ulonglong) to convert.go.

We'll need separate functions for conversion to signed and unsigned longs. (unsigned version should return error when it encounters negative duration). New functions should be covered with tests in convert_test.go.

**Comment by g41797** [comment]
i am on board

**Comment by gavv** [comment]
@g41797 makes sense. Just send a PR  so we can see the actual code when discussing this.

**Comment by g41797** [comment]
After adding of
    
     import "C"

to convert_test.go:

[g41797@BLKF roc]$ go build .
use of cgo in test convert_test.go not supported

According to [import "C" is unsupported in test](https://stackoverflow.com/questions/27930737/import-c-is-unsupported-in-test-looking-for-alternatives) possible solution is "...to put the cgo code in a non-test file..."

wrapper wrapgo2cUlonglongs was added to convert.go

**Comment by g41797** [comment]
Commits of PR - removed 
Fork synced with main 
I am going to merge my development with new sources
