### ISSUE TITLE
Use time.Time for LogMessage.Time

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-go#85]
LogMessage.Time encodes absolute time, in form of nanoseconds since epoch, as uint64. It would be more convenient to encode it as time.Time instead. Comments and tests should be adjusted accordingly.

**Comment by ParasRaba155** [comment]
Hey @roc-streaming/roc-go this is my first time working on an open source project, and I am very novice at that, I have raised a PR and hope to hear your reviews for the PR
